### ISSUE TITLE
Host is blocked, status 403.

### ISSUE THREAD

**Issue by MrCheatEugene** [o7-Fire/NodeNsfwJSAPI#39]
Hello there. 
I am working on a photo hosting website, but today it started failing.
In logs I found one interesting detail:
```
Warning: file_get_contents(https://api.mindustry.me/api/json/graphical/classification/https://vds.mrcheat.ga/temp/phpSI5CjK.png): Failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /var/www/....\.....php on line ...
```
I used api.mindustry.me, because last time it failed with api.yeet.ml, but api.yeet.ml redirected to api.mindustry.me, so I've sticked with that.

When I try to open the faulty link, I get this message: `{"error":"Host is blocked","status":403}`
Domain name of the website is dupix.art, by the way.
Why did this happen? Did I violate some TOS? I did If you can, please respond ASAP. Thanks.

**Comment by MrCheatEugene** [comment]
Update. I've cloned the repo, and hosted your API on the same machine, but no luck.

**Comment by Volas171** [comment]
oops, seems to be an issue from my side, gonna try to fix it asap

**Comment by Volas171** [comment]
Also, the 403 you get is because the API defaults to only accept discord links, however i forgot to remove it on the public one

**Comment by Itzbenz** [comment]
why there is ` Forbidden in /var/www/....\.....php on line`

**Comment by Itzbenz** [comment]
According to my research, if you set env

`ALLOW_ALL_HOST=true` or `ALLOWED_HOST=vds.mrcheat.ga`

you shouldn't get blocked, unless you set `BLOCKED_HOST=vds.mrcheat.ga` in that case both of the option above are ignored and blocked

> Also, the 403 you get is because the API defaults to only accept discord links, however i forgot to remove it on the public one

**Comment by Itzbenz** [comment]
@Volas171 close this if you done

**Comment by Volas171** [comment]
@MrCheatEugene i have also noticed that you're using the old API endpoint, this has been moved to `/api/v2/classification/`
so the request you would be doing is: `https://api.mindustry.me/api/v2/classification/https:/vds.mrcheat.ga/temp/phpSI5CjK.png`
and should return: {"data":`{"Digital":0.9959479609970003,"Neutral":0.9979674220085144,"Drawing":0.0020194610115140676,"Sexy":0.000007890840606705751,"Hentai":0.000002726583034018404,"Porn":0.0000025528013338771416},"model":{"url":"Default","size":"Default"},"timestamp":1667612164410,"hex":"https.vds.mrcheat.ga.temp.phpSI5CjK.png","time":450}`
(some stuff may change)

**Comment by MrCheatEugene** [comment]
ok, thanks
i've already fixed this issue by disabling blocked/allow host verification
right in code
but still thanks for reaching out:)


сб, 5 нояб. 2022 г. в 04:37, Volas171 ***@***.***>:
