### ISSUE TITLE
Error Processing Specific Image

### ISSUE THREAD

**Issue by Akimovx** [o7-Fire/NodeNsfwJSAPI#5]
`https://nsfw-detector-o7.herokuapp.com/api/json/graphical/classification/https://cdn.discordapp.com/avatars/855052349889576980/239445041841099523b9e2c912f390bb.webp?size=1024`

return: `wtf`
status: 500

**Comment by Itzbenz** [comment]
![image](https://user-images.githubusercontent.com/49940811/134652891-2916a7b4-4105-40f0-8e7e-92e87708a8c3.png)
how

**Comment by Itzbenz** [comment]
fixed now return 
`{"error":"Error: Expected image (BMP, JPEG, PNG, or GIF), but got unsupported image type","status":415}`

**Comment by Itzbenz** [comment]
21833b02350f36fe20e4e3e119ed33021c27905d
