### ISSUE TITLE
Gay porn GIF is recognized as "neutral".

### ISSUE THREAD

**Issue by MrCheatEugene** [o7-Fire/NodeNsfwJSAPI#56]
Hi. I was testing this project with different types of nsfw-content, but when it came to gay porn GIF, it recognized GIF as neutral?
What the hell? 

Gif itself: https://cdn.discordapp.com/attachments/846391703862247435/846391726552776734/TalkativeSimilarJay-size_restricted.gif

Can you help me with this ASAP?

**Comment by Itzbenz** [comment]
![image](https://user-images.githubusercontent.com/49940811/209457026-91c70380-5cec-4f99-93ca-35eda83810c4.png)

Due to upstream model and low quality frames, the model loses its accuracy, but I find some frames that give true positive 44 and 21

**Comment by MrCheatEugene** [comment]
K, thank you!
